# only create the secret if injectSecret is false AND existingSecrets is false

{{- if and (not .Values.injectSecretsViaEnv ) (not .Values.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ecsInventory.fullname" . }}
  labels:
    {{- include "ecsInventory.labels" . | nindent 4 }}
type: Opaque
stringData:
  ANCHORE_ECS_INVENTORY_ANCHORE_PASSWORD: {{ .Values.ecsInventory.anchorePassword | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.ecsInventory.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ecsInventory.awsSecretAccessKey | quote }}
{{- end -}}
