logging:
  {{- toYaml .Values.anchoreConfig.logging | nindent 2 }}

services:
  apiext:
    enabled: true
    image_content:
      remove_license_content_from_sbom_return: {{ .Values.anchoreConfig.apiext.image_content.remove_license_content_from_sbom_return }}
    require_auth: true
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    max_request_threads: ${ANCHORE_MAX_REQUEST_THREADS}
    listen: '0.0.0.0'
    port: ${ANCHORE_PORT}
  {{- if .Values.anchoreConfig.apiext.external.enabled }}
    external_tls: {{ .Values.anchoreConfig.apiext.external.useTLS }}
    external_hostname: {{ .Values.anchoreConfig.apiext.external.hostname }}
    external_port: {{ .Values.anchoreConfig.apiext.external.port }}
  {{- end }}
    ssl_enable: ${ANCHORE_SSL_ENABLED}
    ssl_cert: ${ANCHORE_SSL_CERT}
    ssl_key: ${ANCHORE_SSL_KEY}
