service_dir: ${ANCHORE_SERVICE_DIR}
tmp_dir: ${ANCHORE_TMP_DIR}

logging:
  {{- toYaml .Values.anchoreConfig.logging | nindent 2 }}

server:
  {{- toYaml .Values.anchoreConfig.server | nindent 2 }}

allow_awsecr_iam_auto: ${ANCHORE_ALLOW_ECR_IAM_AUTO}
host_id: "${ANCHORE_HOST_ID}"
internal_ssl_verify: {{ .Values.anchoreConfig.internal_ssl_verify }}
image_analyze_timeout_seconds: ${ANCHORE_IMAGE_ANALYZE_TIMEOUT_SECONDS}

global_client_connect_timeout: ${ANCHORE_GLOBAL_CLIENT_CONNECT_TIMEOUT}
global_client_read_timeout: ${ANCHORE_GLOBAL_CLIENT_READ_TIMEOUT}

license_file: ${ANCHORE_LICENSE_FILE}
auto_restart_services: false

max_source_import_size_mb: ${ANCHORE_MAX_IMPORT_SOURCE_SIZE_MB}
max_import_content_size_mb: ${ANCHORE_MAX_IMPORT_CONTENT_SIZE_MB}

max_compressed_image_size_mb: ${ANCHORE_MAX_COMPRESSED_IMAGE_SIZE_MB}

audit:
  enabled: {{ .Values.anchoreConfig.audit.enabled }}
  mode: log
  verbs:
    - post
    - put
    - delete
    - patch
  resource_uris:
{{ include "enterprise.defaultAuditResourceURIs" . | indent 4 }}
{{- with .Values.anchoreConfig.audit.additionalResourceURIs }}
{{- range . }}
    - {{ . | quote }}
{{- end }}
{{- end }}

metrics:
  enabled: ${ANCHORE_ENABLE_METRICS}
  auth_disabled: ${ANCHORE_DISABLE_METRICS_AUTH}

default_admin_password: "${ANCHORE_ADMIN_PASSWORD}"
default_admin_email: ${ANCHORE_ADMIN_EMAIL}

configuration:
  api_driven_configuration_enabled: ${ANCHORE_API_DRIVEN_CONFIGURATION_ENABLED}

keys:
  secret: "${ANCHORE_SAML_SECRET}"
  public_key_path: ${ANCHORE_AUTH_PRIVKEY}
  private_key_path: ${ANCHORE_AUTH_PUBKEY}

user_authentication:
  oauth:
    default_token_expiration_seconds: ${ANCHORE_OAUTH_TOKEN_EXPIRATION}
    refresh_token_expiration_seconds: ${ANCHORE_OAUTH_REFRESH_TOKEN_EXPIRATION}
  sso_require_existing_users: ${ANCHORE_SSO_REQUIRES_EXISTING_USERS}
  allow_api_keys_for_saml_users: {{ .Values.anchoreConfig.user_authentication.allow_api_keys_for_saml_users }}
  max_api_key_age_days: {{ .Values.anchoreConfig.user_authentication.max_api_key_age_days }}
  max_api_keys_per_user: {{ .Values.anchoreConfig.user_authentication.max_api_keys_per_user }}
  remove_deleted_user_api_keys_older_than_days: {{ .Values.anchoreConfig.user_authentication.remove_deleted_user_api_keys_older_than_days }}
  disallow_native_users: {{ .Values.anchoreConfig.user_authentication.disallow_native_users }}
  log_saml_assertions: {{ .Values.anchoreConfig.user_authentication.log_saml_assertions }}
credentials:
  database:
    user: "${ANCHORE_DB_USER}"
    password: "${ANCHORE_DB_PASSWORD}"
    host: "${ANCHORE_DB_HOST}"
    port: "${ANCHORE_DB_PORT}"
    name: "${ANCHORE_DB_NAME}"
  {{- if .Values.anchoreConfig.database.dbConnectArgs }}
  {{- with .Values.anchoreConfig.database.dbConnectArgs }}
    db_connect_args: {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- else }}
    db_connect_args:
      timeout: ${ANCHORE_DB_TIMEOUT}
      ssl: ${ANCHORE_DB_SSL}
    {{- if .Values.anchoreConfig.database.ssl }}
      sslmode: ${ANCHORE_DB_SSL_MODE}
      sslrootcert: ${ANCHORE_DB_SSL_ROOT_CERT}
    {{- end }}
  {{- end }}
    db_pool_size: ${ANCHORE_DB_POOL_SIZE}
    db_pool_max_overflow: ${ANCHORE_DB_POOL_MAX_OVERFLOW}
  {{- with .Values.anchoreConfig.database.engineArgs }}
    db_engine_args: {{- toYaml . | nindent 6 }}
  {{- end }}

account_gc:
  max_resource_gc_chunk: 4096
  max_deletion_threads: 4

vex_annotation_author: {{ .Values.anchoreConfig.vex_annotation_author }}
object_store:
  direct_access: {{ .Values.anchoreConfig.object_store.direct_access }}

{{- with .Values.anchoreConfig.extendedConfig }}
{{- toYaml . | nindent 0 }}
{{- end }}

services:
  apiext:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "apiext") .) | nindent 6 }}
    image_content:
      remove_license_content_from_sbom_return: {{ .Values.anchoreConfig.apiext.image_content.remove_license_content_from_sbom_return }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "api") .) }}"
    port: ${ANCHORE_PORT}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "apiext") .) | nindent 4 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "apiext") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "apiext") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "apiext") .) }}

  analyzer:
    enabled: true
    analyzer_scanner_config: {{- toYaml .Values.anchoreConfig.analyzer.configFile | nindent 6 }}



    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "analyzer") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "analyzer") .) }}"
    port: ${ANCHORE_PORT}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "analyzer") .) | nindent 4 }}
    layer_cache_enable: {{ gt .Values.anchoreConfig.analyzer.layer_cache_max_gigabytes 0.0 }}
    layer_cache_max_gigabytes: {{ .Values.anchoreConfig.analyzer.layer_cache_max_gigabytes }}
    enable_hints: {{ .Values.anchoreConfig.analyzer.enable_hints }}
    enable_owned_package_filtering: true
    keep_image_analysis_tmpfiles: false
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "analyzer") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "analyzer") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "analyzer") .) }}

  catalog:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "catalog") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "catalog") .) }}"
    port: ${ANCHORE_PORT}
    account_prometheus_metrics: {{ .Values.anchoreConfig.catalog.account_prometheus_metrics }}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "catalog") .) | nindent 4 }}
    event_log: {{- toYaml .Values.anchoreConfig.catalog.event_log | nindent 6 }}
    runtime_inventory:
      inventory_ttl_days: ${ANCHORE_ENTERPRISE_RUNTIME_INVENTORY_TTL_DAYS}
      inventory_ingest_overwrite: ${ANCHORE_ENTERPRISE_RUNTIME_INVENTORY_INGEST_OVERWRITE}
    integrations:
      integration_health_report_ttl_days: ${ANCHORE_ENTERPRISE_INTEGRATION_HEALTH_REPORTS_TTL_DAYS}
    image_gc:
      max_worker_threads: ${ANCHORE_CATALOG_IMAGE_GC_WORKERS}
    runtime_compliance:
      object_store_bucket: "runtime_compliance_check"
    import_operation_expiration_days: ${ANCHORE_IMPORT_OPERATION_EXPIRATION_DAYS}
    analysis_queue_priority: {{ .Values.anchoreConfig.catalog.analysis_queue_priority }}
    sbom_vuln_scan:
      auto_scale: {{ .Values.anchoreConfig.catalog.sbom_vuln_scan.auto_scale }}
      batch_size: {{ .Values.anchoreConfig.catalog.sbom_vuln_scan.batch_size }}
      pool_size: {{ .Values.anchoreConfig.catalog.sbom_vuln_scan.pool_size }}
    analysis_archive: {{- include "enterprise.storageConfig" (dict "storeConfig" .Values.anchoreConfig.catalog.analysis_archive "envPrefix" "ANCHORE_ANALYSIS_ARCHIVE" "storeName" "analysis_archive" "context" .) | nindent 6 }}
    object_store: {{- include "enterprise.storageConfig" (dict "storeConfig" .Values.anchoreConfig.catalog.object_store "envPrefix" "ANCHORE_OBJECT_STORE" "storeName" "object_store" "context" .) | nindent 6 }}
    document_views: {{- toYaml .Values.anchoreConfig.catalog.document_views | nindent 6 }}
    system_logs: {{- toYaml .Values.anchoreConfig.catalog.system_logs | nindent 6 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "catalog") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "catalog") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "catalog") .) }}

  simplequeue:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "simplequeue") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "simpleQueue") .) }}"
    port: ${ANCHORE_PORT}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "simplequeue") .) | nindent 4 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "simplequeue") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "simplequeue") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "simplequeue") .) }}

  policy_engine:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "policy_engine") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "policyEngine") .) }}"
    port: ${ANCHORE_PORT}
    catalog_client_conn_timeout: {{ .Values.anchoreConfig.policy_engine.catalog_client_conn_timeout }}
    catalog_client_read_timeout: {{ .Values.anchoreConfig.policy_engine.catalog_client_read_timeout }}
    policy_evaluation_cache_ttl: ${ANCHORE_POLICY_EVAL_CACHE_TTL_SECONDS}
    enable_package_db_load: ${ANCHORE_POLICY_ENGINE_ENABLE_PACKAGE_DB_LOAD}
    enable_user_base_image: {{ .Values.anchoreConfig.policy_engine.enable_user_base_image }}
    vulnerabilities:
      nvd_fallback_to_secondary_cvss: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.nvd_fallback_to_secondary_cvss }}
      extended_support:
        rhel:
          enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.extended_support.rhel.enabled }}
          versions: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.extended_support.rhel.versions }}
      matching:
        exclude:
          {{- if .Values.anchoreConfig.policy_engine.vulnerabilities.matching.exclude.providers }}
          providers: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.exclude.providers | toJson }}
          {{- else }}
          providers: []
          {{- end }}
          {{- if .Values.anchoreConfig.policy_engine.vulnerabilities.matching.exclude.package_types }}
          package_types: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.exclude.package_types | toJson }}
          {{- else }}
          package_types: []
          {{- end }}
        default:
          search:
            by_cpe:
              enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.default.search.by_cpe.enabled }}
        ecosystem_specific:
          dotnet:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.dotnet.search.by_cpe.enabled }}
          dpkg:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.dpkg.search.by_cpe.enabled }}
          golang:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.golang.search.by_cpe.enabled }}
          hex:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.hex.search.by_cpe.enabled }}
          java:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.java.search.by_cpe.enabled }}
          javascript:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.javascript.search.by_cpe.enabled }}
          jvm:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.jvm.search.by_cpe.enabled }}
          python:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.python.search.by_cpe.enabled }}
          rpm:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.rpm.search.by_cpe.enabled }}
          ruby:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.ruby.search.by_cpe.enabled }}
          rust:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.rust.search.by_cpe.enabled }}
          stock:
            search:
              by_cpe:
                # Disabling search by CPE for the stock matcher will entirely disable binary-only matches and is not advised
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.stock.search.by_cpe.enabled }}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "policy_engine") .) | nindent 4 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "policy_engine") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "policy_engine") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "policy_engine") .) }}

  reports:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "reports") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "reports") .) }}"
    port: ${ANCHORE_PORT}
    enable_graphiql: ${ANCHORE_ENTERPRISE_REPORTS_ENABLE_GRAPHIQL}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "reports") .) | nindent 4 }}
    max_async_execution_threads: ${ANCHORE_ENTERPRISE_REPORTS_MAX_ASYNC_EXECUTION_THREADS}
    async_execution_timeout: ${ANCHORE_ENTERPRISE_REPORTS_ASYNC_EXECUTION_TIMEOUT}
    use_volume: {{ .Values.anchoreConfig.reports.use_volume }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "reports") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "reports") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "reports") .) }}

  reports_worker:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "reports_worker") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "reportsWorker") .) }}"
    port: ${ANCHORE_PORT}
    enable_data_ingress: ${ANCHORE_ENTERPRISE_REPORTS_ENABLE_DATA_INGRESS}
    enable_data_egress: ${ANCHORE_ENTERPRISE_REPORTS_ENABLE_DATA_EGRESS}
    data_egress_window: ${ANCHORE_ENTERPRISE_REPORTS_DATA_EGRESS_WINDOW}
    data_refresh_max_workers: ${ANCHORE_ENTERPRISE_REPORTS_DATA_REFRESH_MAX_WORKERS}
    data_load_max_workers: ${ANCHORE_ENTERPRISE_REPORTS_DATA_LOAD_MAX_WORKERS}
    ingress_images_max_workers: {{ .Values.anchoreConfig.reports_worker.ingress_images_max_workers }}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "reports_worker") .) | nindent 4 }}
    event_stream: {{- toYaml .Values.anchoreConfig.reports_worker.event_stream | nindent 6 }}
    runtime_report_generation: {{- toYaml .Values.anchoreConfig.reports_worker.runtime_report_generation | nindent 6 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "reports_worker") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "reports_worker") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "reports_worker") .) }}

  notifications:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "notifications") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "notifications") .) }}"
    port: ${ANCHORE_PORT}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "notifications") .) | nindent 4 }}
    ui_url: ${ANCHORE_ENTERPRISE_UI_URL}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "notifications") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "notifications") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "notifications") .) }}

  data_syncer:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "data_syncer") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "dataSyncer") .) }}"
    port: ${ANCHORE_PORT}
    auto_sync_enabled: ${ANCHORE_DATA_SYNC_AUTO_SYNC_ENABLED}
    upload_dir: {{ .Values.scratchVolume.mountPath }}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "data_syncer") .) | nindent 4 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "data_syncer") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "data_syncer") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "data_syncer") .) }}
