services:
  notifications:
    enabled: true
    require_auth: true
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: '0.0.0.0'
    port: ${ANCHORE_PORT}
    max_request_threads: ${ANCHORE_MAX_REQUEST_THREADS}
    cycle_timers: {{- toYaml .Values.anchoreConfig.notifications.cycle_timers | nindent 6 }}
    ui_url: ${ANCHORE_ENTERPRISE_UI_URL}
    ssl_enable: ${ANCHORE_SSL_ENABLED}
    ssl_cert: ${ANCHORE_SSL_CERT}
    ssl_key: ${ANCHORE_SSL_KEY}
