service_dir: ${ANCHORE_SERVICE_DIR}
tmp_dir: ${ANCHORE_TMP_DIR}

logging:
  {{- toYaml .Values.anchoreConfig.logging | nindent 2 }}

server:
  {{- toYaml .Values.anchoreConfig.server | nindent 2 }}

allow_awsecr_iam_auto: {{ .Values.anchoreConfig.allow_awsecr_iam_auto }}
host_id: "${ANCHORE_HOST_ID}"
internal_ssl_verify: {{ .Values.anchoreConfig.internal_ssl_verify }}
image_analyze_timeout_seconds: {{ .Values.anchoreConfig.image_analyze_timeout_seconds }}

global_client_connect_timeout: ${ANCHORE_GLOBAL_CLIENT_CONNECT_TIMEOUT}
global_client_read_timeout: ${ANCHORE_GLOBAL_CLIENT_READ_TIMEOUT}

license_file: ${ANCHORE_LICENSE_FILE}
auto_restart_services: false

max_source_import_size_mb: {{ .Values.anchoreConfig.max_source_import_size_mb }}
max_import_content_size_mb: {{ .Values.anchoreConfig.max_import_content_size_mb }}

max_compressed_image_size_mb: {{ .Values.anchoreConfig.max_compressed_image_size_mb }}

audit:
  enabled: {{ .Values.anchoreConfig.audit.enabled }}
  mode: log
  verbs:
    - post
    - put
    - delete
    - patch
  resource_uris:
{{ include "enterprise.defaultAuditResourceURIs" . | indent 4 }}
{{- with .Values.anchoreConfig.audit.additionalResourceURIs }}
{{- range . }}
    - {{ . | quote }}
{{- end }}
{{- end }}

metrics:
  enabled: {{ .Values.anchoreConfig.metrics.enabled }}
  auth_disabled: {{ .Values.anchoreConfig.metrics.auth_disabled }}

default_admin_password: "${ANCHORE_ADMIN_PASSWORD}"
default_admin_email: {{ .Values.anchoreConfig.default_admin_email }}

configuration:
  api_driven_configuration_enabled: {{ .Values.anchoreConfig.api_driven_configuration_enabled }}

keys:
  secret: "${ANCHORE_SAML_SECRET}"
{{- with .Values.anchoreConfig.keys.publicKeyFileName }}
  public_key_path: /home/anchore/certs/{{ . }}
{{- else }}
  public_key_path: null
{{- end }}
{{- with .Values.anchoreConfig.keys.privateKeyFileName }}
  private_key_path: /home/anchore/certs/{{ . }}
{{- else }}
  private_key_path: null
{{- end }}

user_authentication:
  oauth:
    default_token_expiration_seconds: {{ .Values.anchoreConfig.user_authentication.oauth.default_token_expiration_seconds }}
    refresh_token_expiration_seconds: {{ .Values.anchoreConfig.user_authentication.oauth.refresh_token_expiration_seconds }}
  sso_require_existing_users: {{ .Values.anchoreConfig.user_authentication.sso_require_existing_users }}
  allow_api_keys_for_saml_users: {{ .Values.anchoreConfig.user_authentication.allow_api_keys_for_saml_users }}
  max_api_key_age_days: {{ .Values.anchoreConfig.user_authentication.max_api_key_age_days }}
  max_api_keys_per_user: {{ .Values.anchoreConfig.user_authentication.max_api_keys_per_user }}
  remove_deleted_user_api_keys_older_than_days: {{ .Values.anchoreConfig.user_authentication.remove_deleted_user_api_keys_older_than_days }}
  disallow_native_users: {{ .Values.anchoreConfig.user_authentication.disallow_native_users }}
  log_saml_assertions: {{ .Values.anchoreConfig.user_authentication.log_saml_assertions }}
credentials:
  database:
    user: "${ANCHORE_DB_USER}"
    password: "${ANCHORE_DB_PASSWORD}"
    host: "${ANCHORE_DB_HOST}"
    port: "${ANCHORE_DB_PORT}"
    name: "${ANCHORE_DB_NAME}"
  {{- if .Values.anchoreConfig.database.dbConnectArgs }}
  {{- with .Values.anchoreConfig.database.dbConnectArgs }}
    db_connect_args: {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- else }}
    db_connect_args:
      timeout: ${ANCHORE_DB_TIMEOUT}
      ssl: ${ANCHORE_DB_SSL}
    {{- if .Values.anchoreConfig.database.ssl }}
      sslmode: ${ANCHORE_DB_SSL_MODE}
      sslrootcert: ${ANCHORE_DB_SSL_ROOT_CERT}
    {{- end }}
  {{- end }}
    db_pool_size: ${ANCHORE_DB_POOL_SIZE}
    db_pool_max_overflow: ${ANCHORE_DB_POOL_MAX_OVERFLOW}
  {{- with .Values.anchoreConfig.database.engineArgs }}
    db_engine_args: {{- toYaml . | nindent 6 }}
  {{- end }}

account_gc:
  max_resource_gc_chunk: 4096
  max_deletion_threads: 4

vex_annotation_author: {{ .Values.anchoreConfig.vex_annotation_author }}
object_store:
  direct_access: {{ .Values.anchoreConfig.object_store.direct_access }}

{{- with .Values.anchoreConfig.extendedConfig }}
{{- toYaml . | nindent 0 }}
{{- end }}

services:
  apiext:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "apiext") .) | nindent 6 }}
    image_content:
      remove_license_content_from_sbom_return: {{ .Values.anchoreConfig.apiext.image_content.remove_license_content_from_sbom_return }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "api") .) }}"
    port: ${ANCHORE_PORT}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "apiext") .) | nindent 4 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "apiext") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "apiext") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "apiext") .) }}

  analyzer:
    enabled: true
    analyzer_scanner_config: {{- toYaml .Values.anchoreConfig.analyzer.configFile | nindent 6 }}



    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "analyzer") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "analyzer") .) }}"
    port: ${ANCHORE_PORT}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "analyzer") .) | nindent 4 }}
    layer_cache_enable: {{ gt .Values.anchoreConfig.analyzer.layer_cache_max_gigabytes 0.0 }}
    layer_cache_max_gigabytes: {{ .Values.anchoreConfig.analyzer.layer_cache_max_gigabytes }}
    enable_hints: {{ .Values.anchoreConfig.analyzer.enable_hints }}
    enable_owned_package_filtering: {{ .Values.anchoreConfig.analyzer.enable_owned_package_filtering }}
    keep_image_analysis_tmpfiles: {{ .Values.anchoreConfig.analyzer.keep_image_analysis_tmpfiles }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "analyzer") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "analyzer") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "analyzer") .) }}

  catalog:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "catalog") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "catalog") .) }}"
    port: ${ANCHORE_PORT}
    account_prometheus_metrics: {{ .Values.anchoreConfig.catalog.account_prometheus_metrics }}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "catalog") .) | nindent 4 }}
    event_log: {{- toYaml .Values.anchoreConfig.catalog.event_log | nindent 6 }}
    runtime_inventory:
      inventory_ttl_days: {{ .Values.anchoreConfig.catalog.runtime_inventory.inventory_ttl_days }}
      inventory_ingest_overwrite: {{ .Values.anchoreConfig.catalog.runtime_inventory.inventory_ingest_overwrite }}
    integrations:
      integration_health_report_ttl_days: {{ .Values.anchoreConfig.catalog.integrations.integration_health_report_ttl_days }}
    image_gc:
      max_worker_threads: {{ .Values.anchoreConfig.catalog.image_gc.max_worker_threads }}
    runtime_compliance:
      object_store_bucket: "runtime_compliance_check"
    import_operation_expiration_days: {{ .Values.anchoreConfig.catalog.import_operation_expiration_days }}
    analysis_queue_priority: {{ .Values.anchoreConfig.catalog.analysis_queue_priority }}
    sbom_vuln_scan:
      auto_scale: {{ .Values.anchoreConfig.catalog.sbom_vuln_scan.auto_scale }}
      batch_size: {{ .Values.anchoreConfig.catalog.sbom_vuln_scan.batch_size }}
      pool_size: {{ .Values.anchoreConfig.catalog.sbom_vuln_scan.pool_size }}
  {{- if and .Values.osaaMigrationJob.enabled .Values.osaaMigrationJob.analysisArchiveMigration.run }}
    analysis_archive: {{- toYaml .Values.osaaMigrationJob.analysisArchiveMigration.analysis_archive | nindent 6 }}
  {{- else }}
    analysis_archive: {{- toYaml .Values.anchoreConfig.catalog.analysis_archive | nindent 6 }}
  {{- end }}
  {{- if and .Values.osaaMigrationJob.enabled .Values.osaaMigrationJob.objectStoreMigration.run }}
    object_store: {{- toYaml .Values.osaaMigrationJob.objectStoreMigration.object_store | nindent 6 }}
  {{- else }}
    object_store: {{- toYaml .Values.anchoreConfig.catalog.object_store | nindent 6 }}
  {{- end }}
    document_views: {{- toYaml .Values.anchoreConfig.catalog.document_views | nindent 6 }}
    system_logs: {{- toYaml .Values.anchoreConfig.catalog.system_logs | nindent 6 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "catalog") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "catalog") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "catalog") .) }}

  simplequeue:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "simplequeue") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "simpleQueue") .) }}"
    port: ${ANCHORE_PORT}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "simplequeue") .) | nindent 4 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "simplequeue") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "simplequeue") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "simplequeue") .) }}

  policy_engine:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "policy_engine") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "policyEngine") .) }}"
    port: ${ANCHORE_PORT}
    catalog_client_conn_timeout: {{ .Values.anchoreConfig.policy_engine.catalog_client_conn_timeout }}
    catalog_client_read_timeout: {{ .Values.anchoreConfig.policy_engine.catalog_client_read_timeout }}
    policy_evaluation_cache_ttl: {{ .Values.anchoreConfig.policy_engine.policy_evaluation_cache_ttl }}
    enable_package_db_load: {{ include "enterprise.policyEngineEnablePackageDBLoad" . }}
    enable_user_base_image: {{ .Values.anchoreConfig.policy_engine.enable_user_base_image }}
    vulnerabilities:
      nvd_fallback_to_secondary_cvss: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.nvd_fallback_to_secondary_cvss }}
      extended_support:
        rhel:
          enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.extended_support.rhel.enabled }}
          versions: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.extended_support.rhel.versions }}
      matching:
        exclude:
          {{- if .Values.anchoreConfig.policy_engine.vulnerabilities.matching.exclude.providers }}
          providers: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.exclude.providers | toJson }}
          {{- else }}
          providers: []
          {{- end }}
          {{- if .Values.anchoreConfig.policy_engine.vulnerabilities.matching.exclude.package_types }}
          package_types: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.exclude.package_types | toJson }}
          {{- else }}
          package_types: []
          {{- end }}
        default:
          search:
            by_cpe:
              enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.default.search.by_cpe.enabled }}
        ecosystem_specific:
          dotnet:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.dotnet.search.by_cpe.enabled }}
          dpkg:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.dpkg.search.by_cpe.enabled }}
          golang:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.golang.search.by_cpe.enabled }}
          hex:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.hex.search.by_cpe.enabled }}
          java:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.java.search.by_cpe.enabled }}
          javascript:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.javascript.search.by_cpe.enabled }}
          jvm:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.jvm.search.by_cpe.enabled }}
          python:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.python.search.by_cpe.enabled }}
          rpm:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.rpm.search.by_cpe.enabled }}
          ruby:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.ruby.search.by_cpe.enabled }}
          rust:
            search:
              by_cpe:
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.rust.search.by_cpe.enabled }}
          stock:
            search:
              by_cpe:
                # Disabling search by CPE for the stock matcher will entirely disable binary-only matches and is not advised
                enabled: {{ .Values.anchoreConfig.policy_engine.vulnerabilities.matching.ecosystem_specific.stock.search.by_cpe.enabled }}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "policy_engine") .) | nindent 4 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "policy_engine") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "policy_engine") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "policy_engine") .) }}

  reports:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "reports") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "reports") .) }}"
    port: ${ANCHORE_PORT}
    enable_graphiql: {{ .Values.anchoreConfig.reports.enable_graphiql }}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "reports") .) | nindent 4 }}
    max_async_execution_threads: {{ .Values.anchoreConfig.reports.max_async_execution_threads }}
    async_execution_timeout: {{ .Values.anchoreConfig.reports.async_execution_timeout }}
    use_volume: {{ .Values.anchoreConfig.reports.use_volume }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "reports") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "reports") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "reports") .) }}

  reports_worker:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "reports_worker") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "reportsWorker") .) }}"
    port: ${ANCHORE_PORT}
    enable_data_ingress: {{ .Values.anchoreConfig.reports_worker.enable_data_ingress }}
    enable_data_egress: {{ .Values.anchoreConfig.reports_worker.enable_data_egress }}
    data_egress_window: {{ .Values.anchoreConfig.reports_worker.data_egress_window }}
    data_refresh_max_workers: {{ .Values.anchoreConfig.reports_worker.data_refresh_max_workers }}
    data_load_max_workers: {{ .Values.anchoreConfig.reports_worker.data_load_max_workers }}
    ingress_images_max_workers: {{ .Values.anchoreConfig.reports_worker.ingress_images_max_workers }}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "reports_worker") .) | nindent 4 }}
    event_stream: {{- toYaml .Values.anchoreConfig.reports_worker.event_stream | nindent 6 }}
    runtime_report_generation: {{- toYaml .Values.anchoreConfig.reports_worker.runtime_report_generation | nindent 6 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "reports_worker") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "reports_worker") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "reports_worker") .) }}

  notifications:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "notifications") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "notifications") .) }}"
    port: ${ANCHORE_PORT}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "notifications") .) | nindent 4 }}
    ui_url: {{ .Values.anchoreConfig.notifications.ui_url | default (include "enterprise.ui.fullname" .) }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "notifications") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "notifications") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "notifications") .) }}

  data_syncer:
    enabled: true
    logging:
      {{- include "enterprise.common.logging" (merge (dict "service" "data_syncer") .) | nindent 6 }}
    endpoint_hostname: ${ANCHORE_ENDPOINT_HOSTNAME}
    listen: "{{ include "enterprise.common.listenAddress" (merge (dict "component" "dataSyncer") .) }}"
    port: ${ANCHORE_PORT}
    auto_sync_enabled: {{ .Values.anchoreConfig.data_syncer.auto_sync_enabled }}
    upload_dir: {{ .Values.scratchVolume.mountPath }}
{{- include "enterprise.anchoreConfig.anchoreService.cycleTimers" (merge (dict "anchoreService" "data_syncer") .) | nindent 4 }}
{{- include "enterprise.anchoreConfig.anchoreService.external" (merge (dict "anchoreService" "data_syncer") .) | nindent 4 }}
    server: {{ include "enterprise.anchoreConfig.anchoreService.server" (merge (dict "anchoreService" "data_syncer") .) }}
  {{- include "enterprise.serviceExtendedConfig" (merge (dict "serviceName" "data_syncer") .) }}
