remote: origin
target-branch: main
chart-dirs:
  - stable
chart-repos:
  - anchore=https://charts.anchore.io/stable
  - bitnami=https://charts.bitnami.com/bitnami
namespace: anchore
release-label: anchore
