remote: origin
target-branch: main
chart-dirs:
  - stable
chart-repos:
  - anchore=https://charts.anchore.io/stable
  - bitnami=https://charts.bitnami.com/bitnami
  - prometheus-community=https://prometheus-community.github.io/helm-charts
namespace: anchore
release-label: anchore
exclude-deprecated: true
