apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-init-ca"
  labels: {{- include "anchore-admission-controller.labels" . | nindent 4 }}
    app: {{ template "anchore-admission-controller.fullname" . }}
    component: admission-server
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels: {{- include "anchore-admission-controller.labels" . | nindent 8 }}
        app: {{ template "anchore-admission-controller.fullname" . }}
        component: admission-server
    spec:
      serviceAccountName: {{ template "anchore-admission-controller.fullname" . }}-init-ca
      restartPolicy: OnFailure
      volumes:
      - name: init-ca-script
        configMap:
          name: {{.Release.Name}}-init-ca
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: create-ca
        image:  "{{ .Values.initCa.image }}"
        command:
        - bash
        - -xe
        - /scripts/init-ca.sh
        volumeMounts:
        - name: init-ca-script
          mountPath: /scripts
        env:
          {{- with .Values.initCa.extraEnv }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- with .Values.initCa.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
