apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8sInventory.fullname" . }}-read-only
  {{- if .Values.annotations }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "k8sInventory.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods","namespaces", "nodes"]
  verbs: ["get", "watch", "list"]
