apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8sInventory.fullname" . }}-read-only-binding
  {{- if .Values.annotations }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "k8sInventory.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8sInventory.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "k8sInventory.fullname" . }}-read-only
  apiGroup: rbac.authorization.k8s.io
