{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "k8sInventory.fullname" . }}
  {{- if .Values.annotations }}
  annotations:
  {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "k8sInventory.labels" . | nindent 4 }}
type: Opaque
stringData:
  ANCHORE_K8S_INVENTORY_ANCHORE_PASSWORD: {{  .Values.k8sInventory.anchore.password }}
{{- end }}
