{{- if and (not .Values.postgresql.enabled) .Values.anchoreEnterpriseGlobal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: anchore-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: anchore-db-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: anchore-enterprise
    app.kubernetes.io/component: database
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  PGUSER: {{ b64enc .Values.postgresql.postgresUser }}
  PGPASSWORD: {{ b64enc .Values.postgresql.postgresPassword }}
  PGDATABASE: {{ b64enc "postgres" }}
  PGHOST: {{$v := .Values.postgresql.externalEndpoint | split ":"}}{{b64enc $v._0}}
  PGPORT: "{{$v := .Values.postgresql.externalEndpoint | split ":"}}{{b64enc $v._1}}"
  ANCHORE_DB: {{ b64enc .Values.postgresql.postgresDatabase }}
{{- end }}