# if the user is setting a global service account name and not overriding it
# for this component, then there is no need to create this service account.
{{- if or (not .Values.anchoreGlobal.serviceAccountName) .Values.anchoreCatalog.serviceAccountName }}
{{- if and .Values.anchoreEnterpriseGlobal.enabled .Values.anchoreCatalog.createServiceAccount .Values.anchoreCatalog.runtimeInventory.reportAnchoreCluster.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "anchore-engine.catalog.serviceAccountName" . }}
  labels:
    {{- with .Values.anchoreCatalog.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreGlobal.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.anchoreCatalog.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "anchore-engine.catalog.fullname" . }}
  labels:
    {{- with .Values.anchoreCatalog.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreGlobal.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.anchoreCatalog.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["pods","namespaces"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "anchore-engine.catalog.fullname" . }}
  labels:
    {{- with .Values.anchoreCatalog.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreGlobal.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.anchoreCatalog.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "anchore-engine.catalog.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "anchore-engine.catalog.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
