{{- if and .Values.anchoreEnterpriseGlobal.enabled .Values.anchoreEnterpriseUi.enabled -}}
{{- $component := "enterprise-ui" -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anchore-engine.enterprise-ui.fullname" . | quote }}
  labels:
    app: {{ include "anchore-engine.fullname" . | quote }}
    component: {{ $component }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.anchoreGlobal.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
data:
  config-ui.yaml: |
    {{- if .Values.anchoreGlobal.internalServicesSsl.enabled }}
    engine_uri: 'https://{{ template "anchore-engine.api.fullname" . }}:{{ .Values.anchoreApi.service.port }}/v1'
    {{- else }}
    engine_uri: 'http://{{ template "anchore-engine.api.fullname" . }}:{{ .Values.anchoreApi.service.port }}/v1'
    {{- end }}
    # This value is overridden by using the `ANCHORE_REDIS_URI` environment variable.
    # redis_ui: $ANCHORE_REDIS_URI
  {{- if .Values.anchoreEnterpriseRbac.enabled }}
    {{- if .Values.anchoreGlobal.internalServicesSsl.enabled }}
    rbac_uri: 'https://{{ template "anchore-engine.api.fullname" . }}:{{ .Values.anchoreEnterpriseRbac.service.apiPort }}/v1'
    {{- else }}
    rbac_uri: 'http://{{ template "anchore-engine.api.fullname" . }}:{{ .Values.anchoreEnterpriseRbac.service.apiPort }}/v1'
    {{- end }}
  {{- end }}
  {{- if .Values.anchoreEnterpriseReports.enabled }}
    {{- if .Values.anchoreGlobal.internalServicesSsl.enabled }}
    reports_uri: 'https://{{ template "anchore-engine.api.fullname" . }}:{{ .Values.anchoreEnterpriseReports.service.port}}/v1'
    {{- else}}
    reports_uri: 'http://{{ template "anchore-engine.api.fullname" . }}:{{ .Values.anchoreEnterpriseReports.service.port}}/v1'
    {{- end }}
  {{- end }}
  {{- if .Values.anchoreEnterpriseNotifications.enabled }}
    {{- if .Values.anchoreGlobal.internalServicesSsl.enabled }}
    notifications_uri: 'https://{{ template "anchore-engine.api.fullname" . }}:{{ .Values.anchoreEnterpriseNotifications.service.port}}/v1'
    {{- else}}
    notifications_uri: 'http://{{ template "anchore-engine.api.fullname" . }}:{{ .Values.anchoreEnterpriseNotifications.service.port}}/v1'
    {{- end }}
  {{- end }}
    # This value is overridden by using the `ANCHORE_APPDB_URI` environment variable.
    # appdb_uri: $ANCHORE_APPDB_URI
    license_path: '/home/anchore/'
    enable_ssl: {{ .Values.anchoreEnterpriseUi.enableSsl }}
    enable_proxy: {{ .Values.anchoreEnterpriseUi.enableProxy }}
    allow_shared_login: {{ .Values.anchoreEnterpriseUi.enableSharedLogin }}
    redis_flushdb: {{ .Values.anchoreEnterpriseUi.redisFlushdb }}
    policy_hub_uri: {{ .Values.anchoreEnterpriseUi.policyHubUri }}
    {{- with .Values.anchoreEnterpriseUi.customLinks }}
    custom_links:
      title: {{ .title }}
      links:
      {{- range .links }}
        {{- with . }}
        - title: {{ .title }}
          uri: {{ .uri }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- with .Values.anchoreEnterpriseUi.enableAddRepositories }}
    enable_add_repositories:
      admin: {{ .admin }}
      standard: {{ .standard }}
    {{- end }}
{{- end -}}
