{{- if and .Values.anchoreEnterpriseGlobal.enabled .Values.anchoreEnterpriseRbac.enabled -}}
{{- $component := "enterprise-rbac" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "anchore-engine.enterprise-rbac.fullname" . }}
  labels:
    app: {{ template "anchore-engine.fullname" . }}
    component: {{ $component }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.anchoreEnterpriseRbac.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreGlobal.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.anchoreGlobal.deploymentAnnotations .Values.anchoreEnterpriseRbac.deploymentAnnotations }}
  annotations:
  {{- with .Values.anchoreGlobal.deploymentAnnotations }}
    {{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.anchoreEnterpriseRbac.deploymentAnnotations }}
    {{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "anchore-engine.fullname" . }}
      component: {{ $component }}
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: {{ template "anchore-engine.fullname" . }}
        component: {{ $component }}
        {{- with .Values.anchoreEnterpriseRbac.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.anchoreGlobal.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      annotations:
      {{- with .Values.anchoreGlobal.annotations }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchoreEnterpriseRbac.annotations }}
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.inject_secrets_via_env }}
        checksum/secrets: {{ include (print $.Template.BasePath "/engine_secret.yaml") . | sha256sum }}
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/engine_configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.anchoreGlobal.securityContext }}
      securityContext:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.anchoreEnterpriseGlobal.imagePullSecretName }}
      containers:
      {{- if .Values.cloudsql.enabled  }}
      - name: cloudsql-proxy
        image: {{ .Values.cloudsql.image.repository }}:{{ .Values.cloudsql.image.tag }}
        imagePullPolicy: {{ .Values.cloudsql.image.pullPolicy }}
        {{- with .Values.anchoreGlobal.containerSecurityContext }}
        securityContext:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        command: ["/cloud_sql_proxy"]
        args:
        {{- if .Values.cloudsql.extraArgs }}
        {{- range $arg := .Values.cloudsql.extraArgs }}
        - {{ quote $arg }}
        {{- end }}
        {{- end }}
        - "-instances={{ .Values.cloudsql.instance }}=tcp:5432"
        {{- if .Values.cloudsql.useExistingServiceAcc }}
        - "-credential_file=/var/{{ .Values.cloudsql.serviceAccSecretName }}/{{ .Values.cloudsql.serviceAccJsonName }}"
        volumeMounts:
        - mountPath: /var/{{ .Values.cloudsql.serviceAccSecretName }}
          name: {{ .Values.cloudsql.serviceAccSecretName }}
          readOnly: true
        {{- end }}
      {{- end }}
      - name: "{{ .Chart.Name }}-{{ $component }}"
        image: {{ .Values.anchoreEnterpriseGlobal.image }}
        imagePullPolicy: {{ .Values.anchoreEnterpriseGlobal.imagePullPolicy }}
        {{- with .Values.anchoreGlobal.containerSecurityContext }}
        securityContext:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        command: ["/bin/sh", "-c"]
        args:
        - {{ print (include "doSourceFile" .) }} /docker-entrypoint.sh anchore-enterprise-manager service start --no-auto-upgrade rbac_manager
        ports:
        - containerPort: {{ .Values.anchoreEnterpriseRbac.service.managerPort }}
          name: rbac
        envFrom:
        {{- if not .Values.inject_secrets_via_env }}
        {{- if .Values.anchoreGlobal.useExistingSecrets }}
        - secretRef:
            name: {{ .Values.anchoreGlobal.existingSecretName }}
        {{- else }}
        - secretRef:
            name: {{ include "anchore-engine.fullname" . }}
        - secretRef:
            name: {{ print (include "anchore-engine.fullname" .) "-admin-pass" }}
        {{- end }}
        {{- end }}
        env:
        {{- with .Values.anchoreGlobal.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.anchoreEnterpriseRbac.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: ANCHORE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: config-volume
          mountPath: /config/config.yaml
          subPath: config.yaml
        {{- if .Values.anchoreGlobal.openShiftDeployment }}
        - name: service-config-volume
          mountPath: /anchore_service_config
        - name: logs
          mountPath: /var/log/anchore
        - name: run
          mountPath: /var/run/anchore
        {{- end }}
        - name: anchore-license
          mountPath: /home/anchore/license.yaml
          subPath: license.yaml
        {{- if (.Values.anchoreGlobal.certStoreSecretName) }}
        - name: certs
          mountPath: /home/anchore/certs/
          readOnly: true
        {{- end }}
        {{- with .Values.anchoreGlobal.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /health
            port: rbac
            {{- if .Values.anchoreGlobal.internalServicesSsl.enabled }}
            scheme: HTTPS
            {{- end }}
          initialDelaySeconds: {{ .Values.anchoreGlobal.probes.liveness.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.anchoreGlobal.probes.liveness.timeoutSeconds }}
          periodSeconds: {{ .Values.anchoreGlobal.probes.liveness.periodSeconds }}
          failureThreshold: {{ .Values.anchoreGlobal.probes.liveness.failureThreshold }}
          successThreshold: {{ .Values.anchoreGlobal.probes.liveness.successThreshold }}
        readinessProbe:
          httpGet:
            path: /health
            port: rbac
            {{- if .Values.anchoreGlobal.internalServicesSsl.enabled }}
            scheme: HTTPS
            {{- end }}
          timeoutSeconds: {{ .Values.anchoreGlobal.probes.readiness.timeoutSeconds }}
          periodSeconds: {{ .Values.anchoreGlobal.probes.readiness.periodSeconds }}
          failureThreshold: {{ .Values.anchoreGlobal.probes.readiness.failureThreshold }}
          successThreshold: {{ .Values.anchoreGlobal.probes.readiness.successThreshold }}
        resources:
          {{ toYaml .Values.anchoreEnterpriseRbac.managerResources | nindent 10 }}
      - name: {{ .Chart.Name }}-rbac-authorizer
        image: {{ .Values.anchoreEnterpriseGlobal.image }}
        imagePullPolicy: {{ .Values.anchoreEnterpriseGlobal.imagePullPolicy }}
        {{- with .Values.anchoreGlobal.containerSecurityContext }}
        securityContext:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        command: ["/bin/sh", "-c"]
        args:
        - {{ print (include "doSourceFile" .) }} /docker-entrypoint.sh anchore-enterprise-manager service start --no-auto-upgrade rbac_authorizer
        envFrom:
        {{- if not .Values.inject_secrets_via_env }}
        {{- if .Values.anchoreGlobal.useExistingSecrets }}
        - secretRef:
            name: {{ .Values.anchoreGlobal.existingSecretName }}
        {{- else }}
        - secretRef:
            name: {{ include "anchore-engine.fullname" . }}
        - secretRef:
            name: {{ print (include "anchore-engine.fullname" .) "-admin-pass" }}
        {{- end }}
        {{- end }}
        env:
        {{- with .Values.anchoreGlobal.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.anchoreEnterpriseRbac.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: ANCHORE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: {{ .Values.anchoreEnterpriseRbac.service.authPort }}
          name: rbac-auth
        volumeMounts:
        - name: anchore-license
          mountPath: /home/anchore/license.yaml
          subPath: license.yaml
        - name: config-volume
          mountPath: /config/config.yaml
          subPath: config.yaml
        {{- if (.Values.anchoreGlobal.certStoreSecretName) }}
        - name: certs
          mountPath: /home/anchore/certs/
          readOnly: true
        {{- end }}
        {{- if .Values.anchoreGlobal.openShiftDeployment }}
        - name: service-config-volume
          mountPath: /anchore_service_config
        - name: logs
          mountPath: /var/log/anchore
        - name: run
          mountPath: /var/run/anchore
        {{- end }}
        {{- with .Values.anchoreGlobal.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          exec:
            command:
              - curl
              - -f
              - 'localhost:{{ .Values.anchoreEnterpriseRbac.service.authPort }}/health'
          initialDelaySeconds: {{ .Values.anchoreGlobal.probes.liveness.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.anchoreGlobal.probes.liveness.timeoutSeconds }}
          periodSeconds: {{ .Values.anchoreGlobal.probes.liveness.periodSeconds }}
          failureThreshold: {{ .Values.anchoreGlobal.probes.liveness.failureThreshold }}
          successThreshold: {{ .Values.anchoreGlobal.probes.liveness.successThreshold }}
        readinessProbe:
          exec:
            command:
              - curl
              - -f
              - 'localhost:{{ .Values.anchoreEnterpriseRbac.service.authPort }}/health'
          timeoutSeconds: {{ .Values.anchoreGlobal.probes.readiness.timeoutSeconds }}
          periodSeconds: {{ .Values.anchoreGlobal.probes.readiness.periodSeconds }}
          failureThreshold: {{ .Values.anchoreGlobal.probes.readiness.failureThreshold }}
          successThreshold: {{ .Values.anchoreGlobal.probes.readiness.successThreshold }}
        resources:
          {{ toYaml .Values.anchoreEnterpriseRbac.authResources | nindent 10 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "anchore-engine.enterprise.fullname" . }}
        {{- if .Values.anchoreGlobal.openShiftDeployment }}
        - name: service-config-volume
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: run
          emptyDir: {}
        {{- end }}
        - name: anchore-license
          secret:
            secretName: {{ .Values.anchoreEnterpriseGlobal.licenseSecretName }}
        {{- if .Values.cloudsql.useExistingServiceAcc }}
        - name: {{ .Values.cloudsql.serviceAccSecretName }}
          secret:
            secretName: {{ .Values.cloudsql.serviceAccSecretName }}
        {{- end }}
        {{- with .Values.anchoreGlobal.certStoreSecretName }}
        - name: certs
          secret:
            secretName: {{ . }}
        {{- end }}
        {{- with .Values.anchoreGlobal.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.anchoreEnterpriseRbac.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchoreEnterpriseRbac.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.anchoreEnterpriseRbac.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with include "anchore-engine.enterprise-rbac.serviceAccountName" . }}
      serviceAccountName: {{ . }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "anchore-engine.enterprise-rbac.serviceName" . }}
  labels:
    app: {{ template "anchore-engine.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ $component }}
    {{- with .Values.anchoreEnterpriseRbac.service.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreGlobal.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.anchoreEnterpriseRbac.service.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.anchoreEnterpriseRbac.service.type }}
  ports:
    - name: rbac
      port: {{ .Values.anchoreEnterpriseRbac.service.managerPort }}
      targetPort: {{ .Values.anchoreEnterpriseRbac.service.managerPort }}
      protocol: TCP
      {{- with .Values.anchoreEnterpriseRbac.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    app: {{ template "anchore-engine.fullname" . }}
    component: {{ $component }}
{{- end -}}
