{{- if (index .Values "anchore-feeds-db" "createExternalDbAssets") }}
{{- if and (hasKey (index .Values "anchore-feeds-db") "enabled")  }}
{{- if and (not (index .Values "anchore-feeds-db" "enabled")) .Values.anchoreEnterpriseGlobal.enabled }}
# Job to sync db and db user with external postgres for Anchore's feeds db
apiVersion: batch/v1
kind: Job
metadata:
  name: ensure-feeds-db
  annotations:
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: ensure-feeds-db
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      {{- if (index .Values "anchore-feeds-db" "imagePullSecretName") }}
      imagePullSecrets:
        - name: {{ (index .Values "anchore-feeds-db" "imagePullSecretName") }}
      {{- end }}
      containers:
        - name: psql
          image: {{ (index .Values "anchore-feeds-db" "image") }}
          command:
            - /bin/bash
            - -exc
            - |   
              echo "Ensure Anchore Feeds DB..."
              
              psql -tc "SELECT 1 FROM pg_database WHERE datname = '$FEEDS_DB'" | grep -q 1 || psql -c "CREATE DATABASE $FEEDS_DB"
              psql -tc "SELECT 1 FROM pg_roles WHERE rolname = '$APPLICATION_USER'" | grep -q 1 && psql -c "ALTER USER $APPLICATION_USER WITH PASSWORD '$APPLICATION_PASSWORD'; GRANT ALL PRIVILEGES ON DATABASE $FEEDS_DB TO $APPLICATION_USER;" | grep -q GRANT || psql -c "CREATE USER $APPLICATION_USER WITH PASSWORD '$APPLICATION_PASSWORD'; GRANT ALL PRIVILEGES ON DATABASE $FEEDS_DB TO $APPLICATION_USER;"
          envFrom:
            - secretRef:
                name: feeds-db-credentials
      restartPolicy: OnFailure
{{- end }}
{{- end }}
{{- end }}