{{- if (index .Values "anchore-feeds-db" "createExternalDbAssets") }}
{{- if and (hasKey (index .Values "anchore-feeds-db") "enabled")  }}
{{- if and (not (index .Values "anchore-feeds-db" "enabled")) .Values.anchoreEnterpriseGlobal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: feeds-db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: feeds-db-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: anchore-enterprise
    app.kubernetes.io/component: database
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  PGUSER: {{ b64enc (index .Values "anchore-feeds-db" "postgresUser") }}
  PGPASSWORD: {{ b64enc (index .Values "anchore-feeds-db" "postgresPassword") }}
  PGDATABASE: {{ b64enc "postgres" }}
  PGHOST: {{$v := (index .Values "anchore-feeds-db" "externalEndpoint") | split ":"}}{{b64enc $v._0}}
  PGPORT: "{{$v := (index .Values "anchore-feeds-db" "externalEndpoint") | split ":"}}{{b64enc $v._1}}"
  FEEDS_DB: {{ b64enc (index .Values "anchore-feeds-db" "postgresDatabase") }}
  APPLICATION_USER: {{ b64enc (index .Values "anchore-feeds-db" "applicationUser") }}
  APPLICATION_PASSWORD: {{ b64enc (index .Values "anchore-feeds-db" "applicationPassword") }}
{{- end }}
{{- end }}
{{- end }}