{{- if .Values.anchoreGlobal.usePreupgradeHook -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "anchore-engine.fullname" . }}-upgrade-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "anchore-engine.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.anchoreGlobal.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreEngineUpgradeJob.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreEnterpriseEngineUpgradeJob.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreEnterpriseFeedsUpgradeJob.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    {{- with .Values.anchoreGlobal.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreEngineUpgradeJob.annotations }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreEnterpriseEngineUpgradeJob.annotations }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.anchoreEnterpriseFeedsUpgradeJob.annotations }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}