postgresql:
  externalEndpoint: "anchore-db-rw.anchore.svc.cluster.local"
  auth:
    username: anchore
    password: anchore-postgres,123
    database: anchore
anchoreConfig:
  default_admin_password: foobar
  database:
    # CI only - sensitive columns stored unencrypted
    disable_db_encryption_unsafe: true
image: anchore/enterprise-dev:nightly
ui:
  image: anchore/anchore-on-prem-ui-dev:nightly
