version: 2.1

jobs:
  lint-charts:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Lint Charts
          command: |
            make lint-chart-engine

  install-charts:
    docker:
      - image: circleci/python:3.6
    resource_class: large
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: |
            make install-chart-engine
            make smoke-tests
            make cluster-down

workflows:
  version: 2.1
  lint-and-install:
    jobs:
      - lint-charts
      - install-charts:
          requires:
            - lint-charts
