version: 2.1

# Note that these ports must match what's actually exposed in
# the k8s cluster; that's done in the config used in creating
# the cluster, e.g.:
# nodes:
#  - role: control-plane
#    extraPortMappings:
#      - containerPort: 30028
#        hostPort: 8228
#
.ssh_forward_port: &ssh_forward_port
  run:
    name: Forward remote-docker ports for testing
    command: |
      ssh -MS anchore-api -fN4 -L 8228:localhost:8228 remote-docker
      ssh -MS k8s-api -fN4 -L 32768:localhost:32768 remote-docker

jobs:
  lint-charts:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Lint Charts
          command: |
            make lint-chart-engine

  install-charts:
    docker:
      - image: circleci/python:3.6
    resource_class: large
    steps:
      - setup_remote_docker
      - checkout
      - <<: *ssh_forward_port
      - run:
          command: |
            make install-chart-engine
            make smoke-tests
            make cluster-down

workflows:
  version: 2.1
  lint-and-install:
    jobs:
      - lint-charts
      - install-charts:
          requires:
            - lint-charts
