{{- $component := "analyzer" -}}

kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "enterprise.analyzer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "enterprise.common.labels" (merge (dict "component" $component) .) | nindent 4 }}
  annotations: {{- include "enterprise.common.annotations" (merge (dict "component" $component) .) | nindent 4 }}
data:
  analyzer_config.yaml: |
    # Anchore analyzer configuration
  {{- with .Values.anchoreConfig.analyzer.configFile }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
