{{- include "enterprise.exclusionCheck" . -}}
{{- include "enterprise.validateDbEncryption" . -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "enterprise.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "enterprise.common.labels" . | nindent 4 }}
  annotations: {{- include "enterprise.common.annotations" . | nindent 4 }}

data:
  config.yaml: |
{{ include "enterprise.configData" . | indent 4 }}
