kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "enterprise.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "enterprise.common.labels" . | nindent 4 }}
  annotations: {{- include "enterprise.common.annotations" . | nindent 4 }}

data:
  config.yaml: |
    # Anchore Service Configuration File, mounted from a configmap
    #
{{- if .Values.configOverride }}
{{ tpl .Values.configOverride . | indent 4 }}
{{- else }}
{{ tpl (.Files.Get "files/default_config.yaml") . | indent 4 }}
{{- end }}
