{{- if .Values.ingress.enabled -}}
{{- $component := "ingress" -}}

{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "enterprise.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "enterprise.common.labels" (merge (dict "component" $component) .) | nindent 4 }}
  annotations: {{- include "enterprise.common.annotations" (merge (dict "component" $component) .) | nindent 4 }}
spec:
{{- if and .Values.ingress.ingressClassName (not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class")) }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- if or .Values.ingress.apiHosts .Values.ingress.uiHosts .Values.ingress.feedsHosts }}
    {{- range $apiHostIndex, $apiHostName := .Values.ingress.apiHosts }}
    - host: {{ $apiHostName | quote }}
      http:
        paths:
        {{- range $apiPathIndex, $apiPath := $.Values.ingress.apiPaths }}
          - path: {{ $apiPath }}
          {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "enterprise.api.fullname" $ }}
                port:
                  number: {{ $.Values.api.service.port }}
          {{- else }}
            backend:
              serviceName: {{ template "enterprise.api.fullname" $ }}
              servicePort: {{ $.Values.api.service.port }}
          {{- end }}
        {{- end }}
    {{- end }}
    {{- range $uiHostIndex, $uiHostName := .Values.ingress.uiHosts }}
    - host: {{ $uiHostName | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.uiPath }}
          {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "enterprise.ui.fullname" $ }}
                port:
                  number: {{ $.Values.ui.service.port }}
          {{- else }}
            backend:
              serviceName: {{ template "enterprise.ui.fullname" $ }}
              servicePort: {{ $.Values.ui.service.port }}
          {{- end }}
    {{- end }}
    {{- range $feedsHostIndex, $feedsHostName := .Values.ingress.feedsHosts }}
    - host: {{ $feedsHostName | quote }}
      http:
        paths:
        {{- range $feedsPathIndex, $feedsPath := $.Values.ingress.feedsPaths }}
          - path: {{ $feedsPath }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "enterprise.feeds.fullname" $ }}
                port:
                  number: {{ $.Values.feeds.service.port }}
          {{- else }}
            backend:
              serviceName: {{ template "enterprise.feeds.fullname" $ }}
              servicePort: {{ $.Values.feeds.service.port }}
          {{- end }}
        {{- end }}
    {{- end }}
  {{- else }}
    - http:
        paths:
        {{- range .Values.ingress.apiPaths }}
          - path: {{ . }}
          {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "enterprise.api.fullname" $ }}
                port:
                  number: {{ $.Values.api.service.port }}
          {{- else }}
            backend:
              serviceName: {{ template "enterprise.api.fullname" $ }}
              servicePort: {{ $.Values.api.service.port }}
          {{- end }}
        {{- end }}
        {{- with .Values.ingress.uiPath }}
          - path: {{ . }}
          {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "enterprise.ui.fullname" $ }}
                port:
                  number: {{ $.Values.ui.service.port }}
          {{- else }}
            backend:
              serviceName: {{ template "enterprise.ui.fullname" $ }}
              servicePort: {{ $.Values.ui.service.port }}
          {{- end }}
        {{- end }}
        {{- range .Values.ingress.feedsPaths }}
          - path: {{ . }}
          {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "enterprise.feeds.fullname" $ }}
                port:
                  number: {{ $.Values.feeds.service.port }}
          {{- else }}
            backend:
              serviceName: {{ template "enterprise.feeds.fullname" $ }}
              servicePort: {{ $.Values.feeds.service.port }}
          {{- end }}
        {{- end }}
  {{- end }}
{{- end -}}
