{{- if or (not .Values.useExistingSecrets) (not .Values.useExistingLicenseSecret) -}}
{{- $license := required "A valid .Values.license is required!" .Values.license -}}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "enterprise.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels: {{- include "enterprise.common.labels" . | nindent 4 }}
  annotations: {{- include "enterprise.common.annotations" . | nindent 4 }}
stringData:
  license.yaml: |
    # Anchore Enterprise License - installed via Helm
    #
{{ toYaml .Values.license | indent 4 }}

{{- end -}}
