{{- $component := "migrate" -}}
{{- if .Values.startMigrationPod -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-enterprise-migrate-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: upgradejob
spec:
  containers:
  - command: [ "/bin/bash", "-c", "--" ]
    args: [ "sleep infinity" ]
    image: {{ .Values.migrationPodImage }}
    imagePullPolicy: {{ .Values.imagePullPolicy }}
    name: enterprise-migrate-db
    env:
      - name: NEW_DB_HOST
        value: {{ .Release.Name }}-postgresql
      - name: OLD_DB_HOST
        valueFrom:
          secretKeyRef:
            key: ANCHORE_DB_HOST
            name: {{ .Values.migrationAnchoreEngineSecretName }}
      - name: NEW_DB_PASSWORD
        value: {{ .Values.postgresql.auth.password }}
      - name: OLD_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: ANCHORE_DB_PASSWORD
            name: {{ .Values.migrationAnchoreEngineSecretName }}
      - name: NEW_DB_USERNAME
        value: {{ .Values.postgresql.auth.username }}
      - name: OLD_DB_USERNAME
        valueFrom:
          secretKeyRef:
            key: ANCHORE_DB_USER
            name: {{ .Values.migrationAnchoreEngineSecretName }}
      - name: OLD_DB_NAME
        valueFrom:
          secretKeyRef:
            key: ANCHORE_DB_NAME
            name: {{ .Values.migrationAnchoreEngineSecretName }}
      - name: NEW_DB_NAME
        value: {{ .Values.postgresql.auth.database }}
{{- end -}}
