{{- if (not .Values.useExistingPullCredSecret) -}}
{{- $imageUsername := required "A valid .Values.imageCredentials.username is required!" .Values.imageCredentials.username -}}
{{- $imagePassword := required "A valid .Values.imageCredentials.password is required!" .Values.imageCredentials.password -}}
{{- $imageEmail := required "A valid .Values.imageCredentials.email is required!" .Values.imageCredentials.email -}}
{{- $imageRegistry := required "A valid .Values.imageCredentials.registry is required!" .Values.imageCredentials.registry -}}

apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ template "enterprise.fullname" . }}-pullcreds
  namespace: {{ .Release.Namespace }}
  labels: {{- include "enterprise.common.labels" . | nindent 4 }}
  annotations: {{- include "enterprise.common.annotations" . | nindent 4 }}
data:
  .dockerconfigjson: {{ template "enterprise.imagePullSecret" . }}

{{- end -}}
