{{- if .Values.reportsWorker.autoscaling.enabled }}
{{- $component := "reportsWorker" -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "enterprise.reportsWorker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "enterprise.common.labels" (merge (dict "component" $component) .) | nindent 4 }}
  annotations: {{- include "enterprise.common.annotations" (merge (dict "component" $component) .) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "enterprise.reportsWorker.fullname" . }}
  minReplicas: {{ .Values.reportsWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.reportsWorker.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.reportsWorker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.reportsWorker.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.reportsWorker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.reportsWorker.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
