{{- if (not .Values.useExistingSecrets) -}}
{{- $component := "ui" -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "enterprise.ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "enterprise.common.labels" (merge (dict "component" $component) .) | nindent 4 }}
  annotations: {{- include "enterprise.common.annotations" (merge (dict "component" $component) .) | nindent 4 }}
type: Opaque
stringData:

{{- if .Values.anchoreConfig.database.ssl }}
  ANCHORE_APPDB_URI: 'postgresql://{{- template "enterprise.ui.dbUser" . -}}:{{- template "enterprise.ui.dbPassword" . -}}@{{ template "enterprise.dbHostname" . }}/{{ index .Values "postgresql" "auth" "database" }}?sslMode={{- .Values.anchoreConfig.database.sslMode -}}'
{{- else }}
  ANCHORE_APPDB_URI: 'postgresql://{{- template "enterprise.ui.dbUser" . -}}:{{- template "enterprise.ui.dbPassword" . -}}@{{ template "enterprise.dbHostname" . }}/{{ index .Values "postgresql" "auth" "database" }}'
{{- end }}

{{- if and (index .Values "ui-redis" "externalEndpoint") (not (index .Values "ui-redis" "chartEnabled")) }}
  ANCHORE_REDIS_URI: '{{ index .Values "ui-redis" "externalEndpoint" }}'
{{- else }}
  ANCHORE_REDIS_URI: 'redis://:{{ index .Values "ui-redis" "auth" "password" }}@{{ template "redis.fullname" . }}-master:6379'
{{- end }}
{{- end }}
