apiVersion: v2
name: anchore-engine
version: 1.12.10
appVersion: 0.9.3
description: Anchore container analysis and policy evaluation engine service
keywords:
 - analysis
 - docker
 - anchore
 - "anchore-engine"
 - image
 - security
 - vulnerability
 - scanner
home: https://anchore.com
sources:
 - https://github.com/anchore/anchore-engine
maintainers:
 - name: zhill
   email: zach@anchore.com
 - name: btodhunter
   email: bradyt@anchore.com
engine: gotpl
icon: https://anchore.com/wp-content/uploads/2016/08/anchore.png
dependencies:
 - name: postgresql
   version: "1.0.1"
   repository: "file://./deps/postgresql"
   condition: postgresql.enabled
 - name: postgresql
   version: "1.0.1"
   repository: "file://./deps/postgresql"
   condition: anchore-feeds-db.enabled,anchoreEnterpriseGlobal.enabled
   alias: anchore-feeds-db
 - name: redis
   version: "10"
   repository: "https://charts.bitnami.com/bitnami"
   condition: anchore-ui-redis.enabled,anchoreEnterpriseGlobal.enabled
   alias: anchore-ui-redis
