apiVersion: v2
name: anchore-engine
version: 1.28.6
appVersion: 1.1.0
description: Anchore container analysis and policy evaluation engine service
keywords:
  - analysis
  - docker
  - anchore
  - "anchore-engine"
  - image
  - security
  - vulnerability
  - scanner
home: https://anchore.com
sources:
  - https://github.com/anchore/anchore-engine
maintainers:
  - name: zhill
    email: zach@anchore.com
  - name: btodhunter
    email: bradyt@anchore.com
engine: gotpl
icon: https://anchoreprd.wpengine.com/wp-content/uploads/2021/12/favicon.png
dependencies:
  - name: postgresql
    version: "1.0.1"
    repository: "file://./deps/postgresql"
    condition: postgresql.enabled
  - name: postgresql
    version: "1.0.1"
    repository: "file://./deps/postgresql"
    condition: anchore-feeds-db.enabled,anchoreEnterpriseGlobal.enabled
    alias: anchore-feeds-db
  - name: postgresql
    version: "1.0.1"
    repository: "file://./deps/postgresql"
    condition: anchore-feeds-gem-db.enabled,anchoreEnterpriseFeeds.gemDriverEnabled
    alias: anchore-feeds-gem-db
  - name: redis
    version: "~18"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: ui-redis.enabled,anchoreEnterpriseGlobal.enabled
    alias: ui-redis
