#!/usr/bin/env bash

set -euo pipefail

. anchore-ci/utils

if [[ "${CI:-false}" == false ]]; then

  print_colorized INFO "Port forwarding to API."; echo

  HELM_INSTALL="${1:?'Missing required parameter: HELM_INSTALL'}"

  print_colorized INFO "Waiting for API to come up."; echo

  podname=$(kubectl get pods | grep -v Name | grep api | cut -d' ' -f1)

  while [[ $(kubectl get pods "${podname}" -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]
    do echo "Waiting for API pod ${podname} to be in Ready state." && sleep 5
  done
  echo "API ${podname} is ready."; echo

  kubectl port-forward svc/${HELM_INSTALL}-anchore-engine-api 8228:8228 &

  print_colorized INFO "Port forwarded to API."
else
  print_colorized INFO "No need to port forward."
fi
