apiVersion: v2
name: feeds
type: application
version: "2.2.0"
appVersion: "5.2.0"
kubeVersion: 1.23.x - 1.27.x || 1.23.x-x - 1.28.x-x
description: Anchore feeds service
keywords:
  - "anchore"
  - "anchore-feeds"
maintainers:
  - name: zhill
    email: zach@anchore.com
  - name: btodhunter
    email: bradyt@anchore.com
  - name: hnguyen
    email: hung.nguyen@anchore.com
icon: https://anchore.com/wp-content/uploads/2016/08/anchore.png
dependencies:
  - name: postgresql
    version: "12.5"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: feeds-db.chartEnabled
    alias: feeds-db
  - name: postgresql
    version: "~12.5"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: gem-db.chartEnabled,anchoreConfig.feeds.drivers.gem.enabled
    alias: gem-db
