apiVersion: v2
name: feeds
type: application
version: "3.0.0"
appVersion: "5.10.0"
kubeVersion: 1.23.x - 1.30.x || 1.23.x-x - 1.30.x-x
description: Anchore feeds service
keywords:
  - "anchore"
  - "anchore-feeds"
icon: https://anchore.com/wp-content/uploads/2016/08/anchore.png
dependencies:
  - name: postgresql
    version: "~12.5"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: feeds-db.chartEnabled
    alias: feeds-db
  - name: postgresql
    version: "~12.5"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: gem-db.chartEnabled,anchoreConfig.feeds.drivers.gem.enabled
    alias: gem-db
deprecated: true
