# Component Catalog — per-service application config overrides
services:
  component_catalog:
    logging:
      {{ include "enterprise.common.ngLogging" (merge (dict "service" "component_catalog") .) | nindent 6 }}
