{{- if .Values.ingress.enabled -}}
{{- $component := "ingress" -}}

{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "feeds.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "feeds.common.labels" . | nindent 4 }}
  {{- with .Values.ingress.labels }}
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  annotations: {{- include "feeds.common.annotations" (merge (dict "nil" true) .) | nindent 4 }}
  {{- with .Values.ingress.annotations }}
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- if .Values.ingress.hosts }}
    {{- range $hostIndex, $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
        {{- range $pathIndex, $path := $.Values.ingress.paths }}
          - path: {{ $path }}
            {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "feeds.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- else }}
            backend:
              serviceName: {{ template "feeds.fullname" $ }}
              servicePort: {{ $.Values.service.port }}
          {{- end }}
        {{- end }}
    {{- end }}
  {{- else }}
    - http:
        paths:
        {{- range .Values.ingress.paths }}
          - path: {{ . }}
          {{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ template "feeds.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- else }}
            backend:
              serviceName: {{ template "feeds.fullname" $ }}
              servicePort: {{ $.Values.service.port }}
          {{- end }}
        {{- end }}
  {{- end }}
{{- end -}}
