{{- if not .Values.useExistingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "feeds.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "feeds.common.labels" . | nindent 4 }}
  annotations: {{- include "feeds.common.annotations" . | nindent 4 }}
type: Opaque
stringData:
  ANCHORE_FEEDS_DB_NAME: {{ index .Values "feeds-db" "auth" "database" | quote }}
  ANCHORE_FEEDS_DB_USER: {{ index .Values "feeds-db" "auth" "username"  | quote }}
  ANCHORE_FEEDS_DB_PASSWORD: {{ index .Values "feeds-db" "auth" "password" | quote }}
  ANCHORE_FEEDS_DB_HOST: {{ include "feeds.dbHostname" . | quote }}
  ANCHORE_FEEDS_DB_PORT: {{ index .Values "feeds-db" "primary" "service" "ports" "postgresql" | quote }}
{{- with .Values.anchoreConfig.keys.secret }}
  ANCHORE_SAML_SECRET: {{ . | quote }}
{{- end }}
{{- if .Values.anchoreConfig.feeds.drivers.github.enabled }}
{{- with .Values.anchoreConfig.feeds.drivers.github.token }}
  ANCHORE_GITHUB_TOKEN: {{ . | quote }}
{{- end }}
{{- end }}
{{- with .Values.anchoreConfig.feeds.drivers.nvdv2.api_key }}
  ANCHORE_NVD_API_KEY: {{ . | quote }}
{{- end }}
{{- if .Values.anchoreConfig.feeds.drivers.gem.enabled }}
  ANCHORE_GEM_DB_HOST: {{ default (include "gem-db.fullname" .) (index .Values "gem-db" "externalEndpoint") | quote }}
  ANCHORE_GEM_DB_NAME: {{ index .Values "gem-db" "auth" "database" | quote }}
  ANCHORE_GEM_DB_USER: {{ index .Values "gem-db" "auth" "username" | quote }}
  ANCHORE_GEM_DB_PASSWORD: {{ index .Values "gem-db" "auth" "password" | quote }}
  ANCHORE_GEM_DB_PORT: {{ index .Values "gem-db" "primary" "service" "ports" "postgresql" | quote }}
{{- end }}
{{- end -}}
