# to let the admission server read the namespace reservations
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: {{ template "anchore-admission-controller.fullname" . }}
rules:
- apiGroups:
  - {{ .Values.apiService.group }}
  resources:
  - {{ template "anchore-admission-controller.fullname" . }}
  verbs:
  - get
  - list
  - watch
  - create
