# to let the admission server read the namespace reservations
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{- include "anchore-admission-controller.labels" . | nindent 4 }}
  name: {{ template "anchore-admission-controller.fullname" . }}
rules:
- apiGroups:
  - {{ .Values.apiService.group }}
  resources:
  - {{ template "anchore-admission-controller.fullname" . }}
  verbs:
  - get
  - list
  - watch
  - create
