apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-controller-config
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version \| replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
  config.json: |-
    {
      "validator": {
        "requestanalysis": {{ .Values.requestAnalysis }}
      },
      "AnchoreEndpoint": "{{ .Values.anchoreEndpoint }}",
      "PolicySelectors": {{ toJson .Values.policySelectors }}
    }
