apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-controller-config
  labels:
    app: {{ template "anchore-admission-controller.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |-
    {
      "validator": {
        "requestanalysis": {{ .Values.requestAnalysis }}
      },
      "AnchoreEndpoint": "{{ .Values.anchoreEndpoint }}",
      "PolicySelectors": {{ toJson .Values.policySelectors }}
    }
