apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "anchore-admission-controller.fullname" . }}
  labels: {{- include "anchore-admission-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "anchore-admission-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels: {{- include "anchore-admission-controller.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "anchore-admission-controller.fullname" . }}
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ template "anchore-admission-controller.name" . }}-certs
      - name: controller-config
        configMap:
          name: {{.Release.Name}}-controller-config
      - name: anchore-auth
        secret:
          secretName: {{ if .Values.existingCredentialsSecret }}{{ .Values.existingCredentialsSecret }}{{ else }}{{ template "anchore-admission-controller.fullname" . }}{{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command:
        - "/anchore-kubernetes-admission-controller"
        - "--audit-log-path=-"
        - "--tls-cert-file=/var/serving-cert/tls.crt"
        - "--tls-private-key-file=/var/serving-cert/tls.key"
        - "--v={{ .Values.logVerbosity }}"
        - "--secure-port={{ .Values.service.internalPort }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.internalPort }}
            scheme: HTTPS
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
          readOnly: true
        - mountPath: /config
          name: controller-config
        - mountPath: /credentials
          name: anchore-auth
        env:
        - name: CONFIG_FILE_PATH
          value: /config/config.json
        - name: CREDENTIALS_FILE_PATH
          value: /credentials/credentials.json
        resources: {{- toYaml .Values.resources | nindent 12 }}
    {{- if .Values.nodeSelector }}
    nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
    tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
    affinity: {{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
