apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: extension-{{ template "anchore-admission-controller.fullname" . }}-authentication-reader-default
  labels: {{- include "anchore-admission-controller.labels" . | nindent 4 }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ template "anchore-admission-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
