apiVersion: v1
kind: Secret
metadata:
  name: {{ template "anchore-admission-controller.fullname" . }}
  labels: {{- include "anchore-admission-controller.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: |
{{ toJson .Values.credentials | b64enc | indent 4 }}
