# Service Account with which the controller operates
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "anchore-admission-controller.fullname" . }}
  labels: {{- include "anchore-admission-controller.labels" . | nindent 4 }}
