apiVersion: v1
kind: Service
metadata:
  name: {{ template "anchore-admission-controller.fullname" . }}
  labels: {{- include "anchore-admission-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ template "anchore-admission-controller.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
