{{- if .Values.apiService.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "anchore-admission-controller.name" . }}-admission.anchore.io
  labels: {{- include "anchore-admission-controller.labels" . | nindent 4 }}
webhooks:
- name: {{ template "anchore-admission-controller.name" . }}-admission.anchore.io
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/{{ .Values.apiService.group }}/v1beta1/imagechecks
    {{- with .Values.apiService.webhook.caBundle }}
    caBundle: {{ . | b64enc }}
    {{- end }}
  rules:
  - operations:
    - CREATE
    apiGroups:
    - ""
    apiVersions:
    - "*"
    resources:
    - pods
  failurePolicy: {{ .Values.apiService.webhook.failurePolicy }}
  namespaceSelector: {{- toYaml .Values.apiService.namespaceSelector | nindent 4 }}
{{- end }}
