name: "Publish charts to repo"
on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: publish charts
      uses: J12934/helm-gh-pages-action@master
      with:
        deploy-branch: gh-pages
        access-token: ${{ secrets.ACCESS_TOKEN }}
