name: Run values converter unit tests

on:
  pull_request:
    paths:
      - 'scripts/enterprise-value-converter/**.py'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install argparse pyyaml

      - name: Run tests
        run: |
          cd scripts/enterprise-value-converter
          python -m unittest tests/*.py
